import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const outlineFillTrackTextConfig: ComponentConfig = {
  componentName: "OutlineFillTrackText",
  importPath: "@/components/remocn/outline-fill-track-text",
  controls: {
    leadText: {
      type: "text-content",
      default: "Keep",
      description: "Lead text",
    },
    valueText: {
      type: "text-content",
      default: "100%",
      description: "Outlined value",
    },
    fontSize: {
      type: "number",
      min: 120,
      max: 520,
      step: 4,
      default: 368,
      description: "Font size",
      hiddenFromList: false,
    },
    enterOffset: {
      type: "number",
      min: 0,
      max: 420,
      step: 4,
      default: 240,
      description: "Vertical entrance offset",
      hiddenFromList: false,
    },
    anchorOffsetX: {
      type: "number",
      min: -400,
      max: 400,
      step: 4,
      default: -84,
      description: "Shared horizontal anchor offset",
      hiddenFromList: false,
    },
    trackDistance: {
      type: "number",
      min: 0,
      max: 1800,
      step: 10,
      default: 0,
      description: "Lead-to-value distance override; zero measures the text",
      hiddenFromList: false,
    },
    wordGap: {
      type: "number",
      min: 0,
      max: 500,
      step: 4,
      default: 220,
      description: "Gap between the lead and value",
      hiddenFromList: false,
    },
    endPadding: {
      type: "number",
      min: 0,
      max: 320,
      step: 4,
      default: 96,
      description: "Trailing edge padding for long values",
      hiddenFromList: false,
    },
    fillDuration: {
      type: "number",
      min: 8,
      max: 45,
      step: 1,
      default: 38,
      description: "Fill duration in frames",
      hiddenFromList: false,
    },
    outlineWidth: {
      type: "number",
      min: 0,
      max: 12,
      step: 0.5,
      default: 3,
      description: "Outline width",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#f4f3f6",
      description: "Fill color",
    },
    outlineColor: {
      type: "color",
      default: "#e6e2ed",
      description: "Outline color",
    },
    backgroundColor: {
      type: "color",
      default: "#030012",
      description: "Background color",
    },
    glowColor: {
      type: "color",
      default: "#64109a",
      description: "Entrance glow color",
    },
    fontWeight: {
      type: "enum",
      default: "700",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },
  durationInFrames: 80,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#030012" },
};
