import { Composition, registerRoot } from "remotion";
import {
  getIntroducingProductDuration,
  IntroducingProduct,
  introducingProductSchema,
} from "../../registry/remocn-templates/introducing-product";

export function IntroducingProductRoot() {
  return (
    <Composition
      id="IntroducingProduct"
      component={IntroducingProduct}
      schema={introducingProductSchema}
      durationInFrames={1596}
      fps={30}
      width={1280}
      height={720}
      calculateMetadata={({ props }) => ({
        durationInFrames: getIntroducingProductDuration(props.timeline),
      })}
      defaultProps={{
        content: {
          productName: "Northstar",
          tagline: "Turn complexity into forward motion.",
          hookLine: "Become the builder",
          contrastLine: "AI cannot replace",
          command: "/show me how the product really works",
          benefit: "Move beyond limits",
          metric: "10× faster",
          montageTitle: "One system for forward motion",
          topicIntro: "Learn all of it",
          loopWords: ["create", "learn", "share", "grow", "repeat"],
          featureCards: [
            {
              eyebrow: "Workspace",
              title: "One place for the whole product story",
              description:
                "Keep research, decisions, and progress in a shared view.",
              stat: "12 active projects",
            },
            {
              eyebrow: "Signals",
              title: "See momentum while it happens",
              description:
                "Turn activity into a clear picture of what matters next.",
              stat: "+46% this week",
            },
            {
              eyebrow: "Knowledge",
              title: "Go from detail to understanding",
              description:
                "Connect notes, examples, and context without losing focus.",
              stat: "9× faster",
            },
          ],
          topics: [
            "Product strategy",
            "Customer insights",
            "Launch systems",
            "Team workflows",
            "Your next idea",
          ],
          logoUrl: "",
          screenshotUrls: [],
        },
        theme: {
          darkBackground: "#050507",
          lightBackground: "#fbfaff",
          darkText: "#f8f7fb",
          lightText: "#111014",
          darkMutedText: "#8e8c98",
          lightMutedText: "#625f69",
          accentColor: "#6d3cff",
          warmColor: "#ff7a33",
          fontFamily:
            "var(--font-geist-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
          canvasScale: 1.001,
          gridSize: 120,
          gridOpacity: 0.12,
          glowBlur: 92,
          glowOpacity: 0.72,
          windowBackground: "#0d0d11",
          windowBorderColor: "#ffffff38",
          windowWidth: 920,
          windowHeight: 520,
          compactWindowWidth: 560,
          compactWindowHeight: 330,
          windowRadius: 30,
        },
        timeline: {
          speed: 1,
          hook: 126,
          command: 90,
          brand: 42,
          productUi: 126,
          speedScene: 99,
          features: 507,
          montage: 78,
          learningLoop: 192,
          topics: 126,
          outro: 210,
        },
        scenes: {
          hook: {
            x: 0,
            y: 0,
            fadeInEnd: 0.07,
            fadeOutStart: 0.43,
            easing: "smooth",
            secondBeatAt: 0.524,
            startFontSize: 290,
            enterFontSize: 74,
            settleFontSize: 64,
            fontWeight: 650,
            letterSpacing: -0.065,
            blur: 13,
            enterOffsetX: 120,
          },
          command: {
            x: 0,
            y: -14,
            fadeInEnd: 0.12,
            fadeOutStart: 0.91,
            easing: "smooth",
            collapsedWidth: 120,
            expandedWidth: 760,
            height: 110,
            paddingX: 38,
            fontSize: 37,
            fontWeight: 560,
            expandEnd: 0.33,
            typeStart: 0.17,
            typeEnd: 0.69,
            cursorX: 346,
            cursorY: 86,
            cursorWidth: 48,
            cursorHeight: 60,
          },
          brand: {
            x: 0,
            y: 0,
            fadeInEnd: 0.24,
            fadeOutStart: 0.81,
            easing: "smooth",
            logoSize: 104,
            startScale: 0.72,
            endScale: 1,
            settleAt: 0.57,
          },
          productUi: {
            x: 0,
            y: 29,
            fadeInEnd: 0.14,
            fadeOutStart: 0.86,
            easing: "smooth",
            startY: 120,
            endY: -40,
            startScale: 0.72,
            endScale: 1.02,
            startRotateX: 18,
            endRotateX: 7,
            startRotateY: -17,
            endRotateY: -6,
            settleAt: 0.67,
          },
          speed: {
            x: 0,
            y: 0,
            fadeInEnd: 0.12,
            fadeOutStart: 0.91,
            easing: "ease-out",
            introFontSize: 62,
            metricFontSize: 44,
            introOutAt: 0.42,
            metricInAt: 0.34,
            countStart: 0.4,
            countEnd: 0.67,
            pillWidth: 360,
            pillHeight: 150,
            pillScale: [3.1, 2.35, 1.62, 1],
          },
          features: {
            x: 0,
            y: 14,
            fadeInEnd: 0.04,
            fadeOutStart: 0.94,
            easing: "smooth",
            beatGap: 0.316,
            cardLifetime: 0.398,
            enterXEven: -860,
            enterXOdd: 220,
            centerX: -460,
            exitXEven: -920,
            exitXOdd: 250,
            startY: 40,
            endY: -70,
            startScale: 0.76,
            peakScale: 1.06,
            endScale: 1.18,
            startRotateX: 13,
            peakRotateX: 4,
            endRotateX: -7,
            startRotateY: -13,
            endRotateY: 7,
            taglineX: 74,
            taglineBottom: 62,
            taglineFontSize: 18,
          },
          montage: {
            x: 0,
            y: 0,
            fadeInEnd: 0.23,
            fadeOutStart: 0.85,
            easing: "smooth",
            titleY: 52,
            titleFontSize: 34,
            cardScale: 0.58,
            spreadStart: 1.35,
            spreadEnd: 0.62,
            cards: [
              { x: -450, y: -170, rotate: -9 },
              { x: 80, y: -225, rotate: 7 },
              { x: -90, y: 125, rotate: -2 },
            ],
          },
          learningLoop: {
            x: 0,
            y: 0,
            fadeInEnd: 0.09,
            fadeOutStart: 0.88,
            easing: "smooth",
            startOrbSize: 210,
            endOrbSize: 330,
            orbScale: 0.68,
            orbitSpeed: 0.032,
            benefitFontSize: 57,
            benefitOutAt: 0.52,
            wordsInAt: 0.48,
            wordsFontSize: 29,
            wordsGap: 22,
            highlightStart: 0.55,
            highlightStep: 14,
            blur: 18,
          },
          topics: {
            x: 0,
            y: 0,
            fadeInEnd: 0.08,
            fadeOutStart: 0.92,
            easing: "smooth",
            introFontSize: 64,
            topicStartAt: 0.3,
            topicStartSize: 150,
            topicEndSize: 84,
            topicBlur: 12,
            topicFontWeight: 620,
          },
          outro: {
            x: 0,
            y: -7,
            fadeInEnd: 0.16,
            fadeOutStart: 0.94,
            easing: "smooth",
            logoSize: 118,
            startScale: 0.58,
            settleAt: 0.33,
            nameRevealAt: 0.5,
            taglineBottom: 145,
            taglineFontSize: 19,
            orbitSpeed: 0.012,
            orbitVerticalScale: 0.38,
            orbits: [
              { radius: 260, phase: 0, size: 48 },
              { radius: 355, phase: 2.2, size: 32 },
              { radius: 440, phase: 4.1, size: 58 },
            ],
            rings: [250, 360, 475],
          },
        },
        className: "",
      }}
    />
  );
}

registerRoot(IntroducingProductRoot);
