// GENERATED FILE — do not edit by hand.
// Run `bun run manifest:build` after changing any registry config.
//
// The playback slice of every registry config: everything a preview needs to
// mount a Player, and nothing it needs only to render the customizer panel.
// Consumers that just play a component (cards, changelog, icon gallery) read
// this instead of importing 263 config modules into the client bundle.

import type { BackdropFill } from "@/registry/remocn/backdrop";

export interface PreviewManifestEntry {
  durationInFrames: number;
  fps: number;
  compositionWidth: number;
  compositionHeight: number;
  previewBackdrop?: BackdropFill;
  defaults: Record<string, unknown>;
}

export const previewManifest: Record<string, PreviewManifestEntry> = {
  accordion: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Is it accessible?",
      content: "Yes. It adheres to the WAI-ARIA design pattern.",
      variant: "default",
      state: "opened",
      speed: 1,
    },
  },
  "alert-dialog": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Delete account?",
      description:
        "This action cannot be undone. This will permanently remove your data from our servers.",
      actionLabel: "Delete",
      cancelLabel: "Cancel",
      state: "opened",
      speed: 1,
    },
  },
  "animated-bar-chart": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      barColor: "#0ea5e9",
      gap: 16,
      staggerFrames: 6,
      speed: 1,
    },
  },
  "animated-line-chart": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      strokeColor: "#22c55e",
      strokeWidth: 4,
      gridColor: "#27272a",
      showDot: true,
      speed: 1,
    },
  },
  "ascii-dissolve": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0d0d10",
    },
    defaults: {
      colorBack: "#0d0d10",
      colorFront: "#f2f2f2",
      cellSize: 22,
      speed: 1,
    },
  },
  "ascii-render": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      glyphSize: 26,
      charset: " .:-=+*#%@",
      colored: false,
      ink: "#9dff9d",
      intensity: 1,
      speed: 1,
    },
  },
  backdrop: {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      fillType: "gradient",
      color: "#6366f1",
      gradient: "linear-gradient(135deg, #6366f1 0%, #a855f7 100%)",
      image: "/hero.png",
      padding: 4,
      radius: 1,
      shadow: "0 20px 60px rgba(0,0,0,0.4)",
    },
  },
  "blur-in": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      state: "revealed",
      blur: 8,
      distance: 12,
      direction: "up",
      speed: 1,
    },
  },
  "blur-out-up": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Clear in, airy out.",
      staggerDelay: 1,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "bottom-up-letters": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Shift",
      staggerDelay: 3,
      distance: 46,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  button: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Continue",
      variant: "default",
      size: "default",
      state: "loading",
      primary: "#171717",
      speed: 1,
    },
  },
  "camera-lens": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      softness: 0.5,
      bloom: 0.5,
      aberration: 0.5,
      vignette: 0.5,
      distortion: 0.05,
      speed: 1,
    },
  },
  caret: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      height: 28,
      width: 3,
      radius: 1,
      blink: true,
      blinkPerSecond: 1,
      color: "#1F1E1D",
      speed: 1,
    },
  },
  "caret-wipe": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0d0d10",
    },
    defaults: {
      direction: "right",
      caretColor: "#C3E88D",
      caretWidth: 3,
      speed: 1,
    },
  },
  "chat-gpt": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#FFFFFF",
    },
    defaults: {
      greeting: "What's on your mind today?",
      placeholder: "Ask anything",
      prompt: "Make a sunset over a calm ocean",
      accentColor: "#2F6FED",
      speed: 1,
    },
  },
  "chat-to-preview-layout": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      startChatRatio: 0.5,
      endChatRatio: 0.25,
      speed: 1,
    },
  },
  "check-list": {
    durationInFrames: 360,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      fontSize: 40,
      itemGap: 18,
      closeGap: 9,
      perStep: 1.6,
      strokeWidth: 3,
      color: "#26242c",
      tickColor: "#6f7f35",
      step: 3,
      speed: 1,
    },
  },
  checkbox: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "",
      size: "default",
      state: "checked",
      primary: "#171717",
      speed: 1,
    },
  },
  "chromatic-wave": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      headline: "MUSIC",
      kicker: "APPLES",
      fill: "#ffffff",
      waveHeight: 28,
      maxDisplacementPx: 39,
      turbulentAmount: 130,
      speed: 1,
    },
  },
  "claude-chat": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#F5F4EF",
    },
    defaults: {
      greeting: "Back at it, Dima",
      placeholder: "Try: draft an email · summarize a doc · plan your week",
      prompt: "Draft a launch tweet for our new release",
      modelName: "Opus 4.8",
      modelTier: "Max",
      accentColor: "#D97757",
      speed: 1,
    },
  },
  "claude-code": {
    durationInFrames: 160,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#2B2A28",
    },
    defaults: {
      title: "Claude Code v2.0.0",
      userName: "Remocn",
      model: "Opus 4.8 • Max 20x",
      cwd: "/users/remocn/code/apps",
      placeholder: 'Try "edit <filepath> to ..."',
      prompt: "edit src/theme.ts to add a dark mode toggle",
      accentColor: "#D97757",
      speed: 1,
    },
  },
  combobox: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      state: "opened",
      query: "",
      revealCount: 0,
      placeholder: "Select a fruit…",
      selectedIndex: -1,
      highlightedIndex: 0,
      speed: 1,
    },
  },
  "command-menu": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      state: "opened",
      query: "",
      revealCount: 0,
      selectedIndex: -1,
      highlightedIndex: 0,
      speed: 1,
    },
  },
  "command-menu-item": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Settings",
      icon: "settings",
      shortcut: "⌘ S",
      state: "selected",
      speed: 1,
    },
  },
  confetti: {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      particleCount: 140,
      power: 17,
      gravity: 0.45,
      size: 13,
      seed: 1,
      speed: 1,
    },
  },
  "context-menu": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      state: "opened",
      highlightedIndex: 1,
      speed: 1,
    },
  },
  "crt-screen": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      curvature: 1,
      scanlines: 1,
      maskScale: 2,
      vignette: 1,
      speed: 1,
    },
  },
  "crumple-toss": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      at: 6,
      crumpleSteps: 4,
      tossSteps: 5,
      direction: -35,
      distance: 440,
      spin: 220,
      segments: 9,
      layers: 2,
      randomness: 0.6,
      crushTo: 0.34,
      seed: "toss",
      step: 3,
      speed: 1,
    },
  },
  cursor: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      variant: "arrow",
      size: 28,
      rippleColor: "#171717",
      speed: 1,
    },
  },
  dialog: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Edit profile",
      description:
        "Make changes to your profile here. Click save when you're done.",
      actionLabel: "Save changes",
      cancelLabel: "Cancel",
      state: "opened",
      speed: 1,
    },
  },
  displacement: {
    durationInFrames: 72,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      grid: 60,
      cellAspect: 1,
      shift: 1,
      aberration: 1,
      grain: 0.5,
      stagger: 0.45,
      speed: 1,
    },
  },
  "dither-dissolve": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      shape: "simplex",
      colorBack: "#141318",
      colorFront: "#8f88ae",
      speed: 1,
    },
  },
  drawer: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Edit profile",
      description:
        "Make changes to your profile here. Click save when you're done.",
      actionLabel: "Save changes",
      cancelLabel: "Cancel",
      state: "opened",
      speed: 1,
    },
  },
  drift: {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      grow: 0.035,
      speed: 1,
    },
  },
  "dropdown-menu": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Options",
      state: "opened",
      highlightedIndex: 0,
      speed: 1,
    },
  },
  "dropdown-menu-item": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Profile",
      state: "hover",
      speed: 1,
    },
  },
  "ecosystem-constellation": {
    durationInFrames: 240,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "gradient",
      value: "radial-gradient(ellipse at center, #14101e 0%, #05030a 75%)",
    },
    defaults: {
      satelliteCount: 6,
      centerLabel: "V",
      accentColor: "#a855f7",
      speed: 1,
    },
  },
  "ember-burn": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      patches: 5,
      edgeSoftness: 0.07,
      contentBias: 0.6,
      heat: 0.5,
      glowColor: "#ff7a2f",
      emberAmount: 0.5,
      speed: 1,
    },
  },
  "extrude-pop": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      letter: "WIN",
      bodyColor: "#e8192b",
      faceColor: "#ffffff",
      minimaxRadius: 80,
      extrudeAngleDeg: -58.6,
      extrudeEndFrame: 48,
      speed: 1,
    },
  },
  "fade-through": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      fromText: "Calm transitions.",
      toText: "Fade through content.",
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "focus-blur-resolve": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Focus resolves clearly.",
      blur: 14,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "focus-pull": {
    durationInFrames: 114,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      blur: 16,
      speed: 1,
    },
  },
  "github-sponsors": {
    durationInFrames: 270,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      account: "remocn",
      accentColor: "#db61a2",
      theme: "light",
      speed: 1,
    },
  },
  "github-stars": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      repo: "Remocn/remocn",
      totalStars: 24813,
      orientation: "horizontal",
      accentColor: "#ffbb00",
      theme: "light",
      speed: 1,
    },
  },
  "glass-code-block": {
    durationInFrames: 180,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "image",
      src: "/bg.jpg",
    },
    defaults: {
      title: "hero.tsx",
      width: 760,
      height: 460,
      fontSize: 16,
      glassColor: "rgba(10, 10, 10, 0.6)",
      staggerFrames: 4,
      showTrafficLights: true,
      speed: 1,
    },
  },
  "glass-code-walk": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "image",
      src: "/bg.jpg",
    },
    defaults: {
      title: "scene.tsx",
      zoom: 2.6,
      fontSize: 18,
      staggerFrames: 10,
      width: 880,
      height: 420,
      speed: 1,
    },
  },
  "glitch-cut": {
    durationInFrames: 78,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      intensity: 1,
      slices: 24,
      rgbSplit: 1,
      blockNoise: 0.6,
      speed: 1,
    },
  },
  "gooey-morph": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      word: "HELLO",
      fill: "#f2f2f2",
      fontFamily: "'Bodoni Moda', Georgia, serif",
      blurRadius: 6,
      displaceAmount: 20,
      barTravelFrames: 30,
      speed: 1,
    },
  },
  "grain-dissolve": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      shape: "blob",
      noise: 0.3,
      zoom: 2,
      colorBack: "#141318",
      speed: 1,
    },
  },
  "grid-wave": {
    durationInFrames: 84,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      tileSize: 90,
      waveWidth: 0.16,
      lift: 2,
      gap: 0.12,
      tint: "#8fb4ff",
      direction: "ripple",
      speed: 1,
    },
  },
  "halftone-print": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#26231d",
    },
    defaults: {
      dotSize: 10,
      angle: 0,
      misregistration: 1.2,
      paperTint: "#f4efe4",
      speed: 1,
    },
  },
  "hand-count": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      to: 1284,
      from: 0,
      durationSteps: 18,
      decimals: 0,
      prefix: "",
      suffix: "",
      fontSize: 96,
      color: "#26242c",
      ease: "in-out",
      seed: "count",
      step: 3,
      speed: 1,
    },
  },
  handwrite: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      text: "Made by hand",
      fontSize: 72,
      perStep: 1.6,
      weight: "600",
      color: "#26242c",
      align: "center",
      step: 3,
      speed: 1,
    },
  },
  hologram: {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#04070d",
    },
    defaults: {
      tint: "#63e8ff",
      glow: 1,
      ghost: 1,
      flicker: 1,
      intensity: 1,
      speed: 1,
    },
  },
  "icon-activity": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-alert-triangle": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-arrow-down": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-arrow-left": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-arrow-right": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-arrow-up": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-at-sign": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-award": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-bar-chart-3": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-bell": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-bookmark": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-calendar": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-camera": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-check": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-check-circle": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-chevron-down": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-chevron-left": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-chevron-right": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-chevron-up": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-clock": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-cloud": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-code": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-copy": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-credit-card": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-crown": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-database": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-dollar-sign": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-download": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-external-link": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-eye": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-eye-off": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-file-text": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-filter": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-flame": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-folder": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-gem": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-gift": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-globe": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-heart": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-help-circle": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-home": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-image": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-inbox": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-info": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-key": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-layout-grid": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-link": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-loader": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-lock": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-log-out": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-mail": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-maximize": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-menu": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-message-circle": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-mic": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-monitor": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-moon": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-more-horizontal": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-package": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-party-popper": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-pause": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-pencil": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-phone": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-play": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-plus": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-plus-circle": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-refresh-cw": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-rocket": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-save": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-scatter": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      count: 15,
      color: "#fafafa",
      coverColor: "#0a0a0a",
      flyDistance: 260,
      speed: 1,
    },
  },
  "icon-search": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-send": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-settings": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-share-2": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-shield": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-shopping-cart": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-skip-forward": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-smartphone": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-sparkles": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: true,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-star": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-sun": {
    durationInFrames: 85,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-tag": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-target": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-terminal": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-thumbs-up": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-timer": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-trash": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-trending-down": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-trending-up": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-trophy": {
    durationInFrames: 85,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-upload": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-user": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-user-plus": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-users": {
    durationInFrames: 80,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-video": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-volume-2": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-volume-x": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-wallet": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-x": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-x-circle": {
    durationInFrames: 70,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "icon-zap": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 48,
    compositionHeight: 48,
    defaults: {
      animation: "both",
      loop: false,
      size: 48,
      color: "#171717",
      strokeWidth: 2,
      speed: 1,
    },
  },
  "infinite-bento-pan": {
    durationInFrames: 300,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#050505",
    },
    defaults: {
      panSpeed: 1,
      accentColor: "#7c3aed",
      speed: 1,
    },
  },
  "infinite-marquee": {
    durationInFrames: 180,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#fafafa",
    },
    defaults: {
      text: "ship · build · animate · ",
      fontSize: 120,
      color: "#171717",
      fontWeight: "700",
      pixelsPerFrame: 4,
      stroke: false,
      strokeColor: "#171717",
      speed: 1,
    },
  },
  "ink-arrow": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      curvature: 0.35,
      strokeWidth: 8,
      pressure: 0.2,
      release: 1,
      grain: 1,
      headSize: 24,
      drawDur: 36,
      headDur: 12,
      color: "#26242c",
      seed: "arrow",
      step: 3,
      speed: 1,
    },
  },
  "ink-underline": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      width: 420,
      color: "#6f7f35",
      thickness: 9,
      pressure: 1,
      release: 0.15,
      grain: 1,
      durationSteps: 5,
      seed: "ink",
      step: 3,
      speed: 1,
    },
  },
  "inline-highlight": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      before: "Ship faster with ",
      highlight: "remocn",
      after: ".",
      baseColor: "#171717",
      highlightColor: "#ff5e3a",
      fontSize: 72,
      fontWeight: "600",
      speed: 1,
    },
  },
  input: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      placeholder: "you@example.com",
      value: "remotion@remocn.dev",
      size: "default",
      state: "typing",
      primary: "#171717",
      speed: 1,
    },
  },
  "kinetic-center-build": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Words push left.",
      entryOffset: 88,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "kinetic-warp": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "REM\nOCN",
      textColor: "#FFFFFF",
      fontFamily: "Passion One",
      fontUrl:
        "https://fonts.googleapis.com/css2?family=Passion+One:wght@400;700;900&display=block",
      fontWeight: "700",
      fontSize: 107.1,
      layerScale: 480,
      keyframeStride: 20,
      speed: 1,
    },
  },
  "lens-zoom": {
    durationInFrames: 112,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      lensSteps: 9,
      blurSamples: 7,
      shakeAmount: 50,
      shakeTranslatePx: 73,
      speed: 1,
    },
  },
  "line-by-line-slide": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Think different.\nDo more.",
      distance: 48,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "live-code-compilation": {
    durationInFrames: 260,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      accentColor: "#3b82f6",
      speed: 1,
    },
  },
  "logo-enter": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      diameter: 118,
      overlap: 38,
      ringColor: "#fff",
      orientation: "horizontal",
      stagger: 7,
      speed: 1,
    },
  },
  "marker-highlight": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      before: "Made for ",
      highlight: "builders",
      after: ".",
      markerColor: "#facc15",
      baseColor: "#171717",
      highlightedTextColor: "#171717",
      fontSize: 72,
      fontWeight: "600",
      speed: 1,
    },
  },
  "mask-reveal-up": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Designed to move.\nBuilt to focus.",
      distance: 30,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "matrix-decode": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "DECRYPTED",
      charset: "!@#$%^&*()_+-=<>?/\\|",
      fontSize: 72,
      color: "#22c55e",
      fontWeight: "600",
      revealDuration: 60,
      speed: 1,
    },
  },
  "message-bubble": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      text: "Yep, pushing it live now",
      variant: "incoming",
      reaction: "🔥",
      state: "visible",
      speed: 1,
    },
  },
  "micro-scale-fade": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Welcome to motion.",
      scaleFrom: 0.96,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "number-wheel": {
    durationInFrames: 112,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      from: 0,
      to: 24813,
      fontSize: 120,
      color: "#171717",
      speed: 1,
    },
  },
  opencode: {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#000000",
    },
    defaults: {
      placeholder: "Ask anything... ",
      query: '"What is the tech stack of this project?"',
      agentName: "Build",
      modelName: "Kimi K2.5",
      provider: "Moonshot AI",
      accentColor: "#2B7FFF",
      speed: 1,
    },
  },
  "page-turn": {
    durationInFrames: 128,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      angle: -7,
      poses: 8,
      speed: 1,
    },
  },
  "paper-sticker": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      at: 0,
      padding: "10px 16px",
      background: "#fbfaf6",
      maxTilt: 2.6,
      seed: "sticker",
      step: 3,
      speed: 1,
    },
  },
  "paper-wobble": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      amp: 1.4,
      rotAmp: 0.35,
      seed: "wobble",
      step: 3,
      speed: 1,
    },
  },
  "particle-dissolve": {
    durationInFrames: 84,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      particleSize: 4,
      scatter: 0.08,
      shimmer: 0.6,
      aberration: 0.5,
      direction: "reveal",
      stagger: 0.55,
      speed: 1,
    },
  },
  "per-character-rise": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "One more thing.",
      distance: 32,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "per-word-crossfade": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      fromText: "Beautifully simple.",
      toText: "Designed for focus.",
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "perlin-dissolve": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      colorFront: "#8f88ae",
      colorBack: "#141318",
      softness: 0.1,
      speed: 1,
    },
  },
  "perspective-marquee": {
    durationInFrames: 240,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#050505",
    },
    defaults: {
      fontSize: 84,
      color: "#fafafa",
      fontWeight: "700",
      pixelsPerFrame: 2,
      rotateY: -28,
      rotateX: 8,
      perspective: 1200,
      fadeColor: "#050505",
      speed: 1,
    },
  },
  "perspective-squeeze": {
    durationInFrames: 225,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      upperText: "REMOCN",
      lowerText: "BEST",
      fill: "#f2f2f2",
      upperFontFamily: "Impact, 'Arial Narrow', sans-serif",
      lowerFontFamily: "Impact, 'Arial Narrow', sans-serif",
      lineGap: 50,
      speed: 1,
    },
  },
  "pixelate-region": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      cellSize: 24,
      speed: 1,
    },
  },
  polaroid: {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      caption: "first light",
      captionAt: 0,
      width: 652,
      captionSize: 36,
      step: 3,
      speed: 1,
    },
  },
  popover: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Dimensions",
      description: "Set the dimensions for the layer.",
      side: "bottom",
      width: 288,
      state: "opened",
      speed: 1,
    },
  },
  progress: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      value: 62,
      width: 320,
      showLabel: true,
      speed: 1,
    },
  },
  "push-through": {
    durationInFrames: 112,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      zoom: 2.4,
      blur: 14,
      speed: 1,
    },
  },
  radio: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "",
      size: "default",
      state: "checked",
      primary: "#171717",
      speed: 1,
    },
  },
  reel: {
    durationInFrames: 160,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0b0b0c",
    },
    defaults: {
      width: 1180,
      height: 676,
      radius: 16,
      step: 20,
      reveal: 13,
      speed: 1,
    },
  },
  resizable: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      ratio: 0.5,
      handleState: "idle",
      direction: "horizontal",
      speed: 1,
    },
  },
  "rgb-glitch-text": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "GLITCH",
      fontSize: 96,
      color: "#171717",
      fontWeight: "700",
      glitchAt: 20,
      glitchDuration: 8,
      intensity: 6,
      seed: "glitch",
      speed: 1,
    },
  },
  "ripple-zoom": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      zoom: 4,
      intensity: 0.5,
      softness: 0.5,
      colorBack: "#141318",
      speed: 1,
    },
  },
  "rolling-number": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      from: 0,
      to: 24813,
      fontSize: 120,
      color: "#171717",
      speed: 1,
    },
  },
  "rolodex-flip": {
    durationInFrames: 110,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      interval: 20,
      flipDuration: 10,
      speed: 1,
    },
  },
  "scale-down-fade": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Quietly refined.",
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "scribble-circle": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f1eee7",
    },
    defaults: {
      laps: 1.15,
      strokeWidth: 14,
      pressure: 0.2,
      grain: 1,
      durationSteps: 10,
      color: "#6f7f35",
      seed: "scribble",
      step: 3,
      speed: 1,
    },
  },
  "security-cam": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      compression: 0.7,
      blockSize: 10,
      noise: 0.6,
      intensity: 1,
      speed: 1,
    },
  },
  select: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Select a fruit",
      state: "opened",
      selectedIndex: 1,
      highlightedIndex: -1,
      speed: 1,
    },
  },
  "select-item": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Banana",
      state: "selected",
      speed: 1,
    },
  },
  "shader-caustics": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      scale: 5.2,
      intensity: 1,
      accent: "#7F57FF",
      accentAmount: 0,
    },
  },
  "shader-color-panels": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      density: 3,
      length: 1.1,
      colorBack: "#12121a",
    },
  },
  "shader-dithering": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      size: 2,
      colorBack: "#12121a",
      colorFront: "#6a6a85",
    },
  },
  "shader-dot-orbit": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      size: 1,
      spreading: 1,
      colorBack: "#12121a",
    },
  },
  "shader-gem-smoke": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      colorBack: "#0a0a10",
      innerDistortion: 0.8,
      outerDistortion: 0.6,
      size: 0.8,
    },
  },
  "shader-god-rays": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      intensity: 0.8,
      density: 0.3,
      bloom: 0.4,
      colorBack: "#12121a",
    },
  },
  "shader-grain-gradient": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      softness: 0.6,
      intensity: 0.2,
      noise: 0.15,
      colorBack: "#12121a",
    },
  },
  "shader-liquid-metal": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      distortion: 0.1,
      repetition: 1.5,
      contour: 0.4,
      colorBack: "#2a2a30",
      colorTint: "#8a8a95",
    },
  },
  "shader-mesh-gradient": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      distortion: 0.6,
      swirl: 0.1,
    },
  },
  "shader-metaballs": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      count: 10,
      size: 0.83,
      colorBack: "#12121a",
    },
  },
  "shader-neuro-noise": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      brightness: 0.05,
      contrast: 0.3,
      colorBack: "#12121a",
      colorMid: "#4a4a68",
    },
  },
  "shader-perlin-noise": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      proportion: 0.35,
      softness: 0.1,
      colorBack: "#12121a",
      colorFront: "#6a6a85",
    },
  },
  "shader-pulsing-border": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      thickness: 0.1,
      roundness: 0.25,
      intensity: 0.2,
      colorBack: "#12121a",
    },
  },
  "shader-simplex-noise": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      stepsPerColor: 2,
      softness: 0.1,
    },
  },
  "shader-smoke-ring": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      radius: 0.25,
      thickness: 0.65,
      scale: 0.8,
      colorBack: "#12121a",
    },
  },
  "shader-spiral": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      density: 1,
      strokeWidth: 0.5,
      softness: 0.2,
      colorBack: "#12121a",
    },
  },
  "shader-strata": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      layers: 14,
      amplitude: 0.16,
      accent: "#6733FF",
      accentAmount: 0,
    },
  },
  "shader-swirl": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      bandCount: 4,
      twist: 0.1,
      softness: 0.2,
      colorBack: "#12121a",
    },
  },
  "shader-voronoi": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      distortion: 0.4,
      gap: 0.04,
      glow: 0,
      colorGap: "#12121a",
    },
  },
  "shader-warp": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      distortion: 0.2,
      swirl: 0.4,
      softness: 1,
      proportion: 0.5,
    },
  },
  "shader-water": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      waves: 0.3,
      caustic: 0.08,
      highlights: 0.06,
      colorBack: "#16202b",
    },
  },
  "shader-weave": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      speed: 1,
      scale: 22,
      warp: 0.03,
      accent: "#6733FF",
      accentAmount: 0,
    },
  },
  "shared-axis-y": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      fromText: "Layered navigation.",
      toText: "Hierarchy made clear.",
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "shared-axis-z": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      fromText: "Zooming between states.",
      toText: "Elevate and settle.",
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "sheen-slide-in": {
    durationInFrames: 75,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Introducing",
      fontSize: 72,
      baseColor: "#18181b",
      sheenColor: "#4f8ef7",
      fontWeight: "600",
      speed: 1,
    },
  },
  sheet: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Edit profile",
      description:
        "Make changes to your profile here. Click save when you're done.",
      actionLabel: "Save changes",
      cancelLabel: "Cancel",
      state: "opened",
      speed: 1,
    },
  },
  "shimmer-sweep": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "Generating",
      baseColor: "#3f3f46",
      shineColor: "#fafafa",
      fontSize: 96,
      fontWeight: "700",
      speed: 1,
    },
  },
  "short-slide-down": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Build from above.",
      entryOffset: 28,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "short-slide-right": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Move with intent.",
      distance: 24,
      staggerDelay: 3,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "simulated-cursor": {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      color: "#ffffff",
      size: 32,
      speed: 1,
    },
  },
  skeleton: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      layout: "card",
      state: "loading",
      speed: 1,
    },
  },
  "skeleton-block": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      width: 240,
      height: 20,
      radius: 6,
      speed: 1,
    },
  },
  "slide-swap": {
    durationInFrames: 210,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      axis: "x",
      inDistance: 0.28,
      outDistance: 0.1,
      slideFrames: 30,
      speed: 1,
    },
  },
  slider: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      value: 40,
      thumbState: "idle",
      width: 320,
      showValue: true,
      speed: 1,
    },
  },
  "slot-machine-roll": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      from: "$99",
      to: "$199",
      fontSize: 120,
      color: "#171717",
      fontWeight: "700",
      speed: 1,
    },
  },
  "smoke-dissolve": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      ringColor: "#8f88ae",
      colorBack: "#141318",
      speed: 1,
    },
  },
  "soft-blur-in": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Think different.",
      blur: 12,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  spinner: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      size: 20,
      strokeWidth: 2.5,
      speed: 1,
    },
  },
  "spring-scale-in": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Fast. Crisp. Fluid.",
      staggerDelay: 3,
      scaleFrom: 0.7,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "spring-settle": {
    durationInFrames: 213,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      enterScale: 1.24,
      enterStagger: 3,
      exitScale: 0.84,
      exitFrames: 6,
      speed: 1,
    },
  },
  stage: {
    durationInFrames: 300,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      preset: "smooth-descent",
      shake: 0,
      seed: "remocn-smooth-descent",
      backdrop: "linear-gradient(145deg, #17181d 0%, #09090b 72%)",
      rotateX: 14,
      rotateY: -20,
      perspective: 900,
      scale: 0.86,
      radius: 1.4,
      reflection: 0.24,
      shadow: 0.7,
      light: 0.55,
    },
  },
  "staggered-fade-up": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "Ship faster with remocn",
      staggerDelay: 4,
      distance: 20,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  stepper: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      activeIndex: 1,
      speed: 1,
    },
  },
  "stretch-in": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      text: "REMOCN",
      fill: "#ffffff",
      fontSize: 510,
      entryStagger: 3,
      travelFrames: 33,
      vertexLagFrames: 3.5,
      speed: 1,
    },
  },
  "strikethrough-replace": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      from: "$49/mo",
      to: "Free",
      lineColor: "#ff5e3a",
      fontSize: 96,
      color: "#171717",
      fontWeight: "700",
      speed: 1,
    },
  },
  "sustained-glitch": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      intensity: 1,
      frequency: 1,
      slices: 24,
      seed: 1,
      speed: 1,
    },
  },
  "swirl-dissolve": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      bandCount: 10,
      softness: 0.35,
      colorBack: "#141318",
      speed: 1,
    },
  },
  switch: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "",
      size: "default",
      state: "checked",
      primary: "#171717",
      speed: 1,
    },
  },
  tabs: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      state: "Account",
      variant: "pill",
      speed: 1,
    },
  },
  "terminal-cursor-zoom": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0B0B0C",
    },
    defaults: {
      command: "npx shadcn add @remocn/terminal-cursor-zoom",
      zoom: 2.8,
      fontSize: 20,
      prompt: "$",
      title: "~/code/remocn-demo",
      speed: 1,
    },
  },
  "terminal-simulator": {
    durationInFrames: 240,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#050505",
    },
    defaults: {
      prompt: "$",
      title: "~/projects/remocn",
      background: "#0a0a0a",
      chromeColor: "#1a1a1a",
      fontSize: 18,
      charsPerFrame: 1,
      chunkSize: 1,
      speed: 1,
    },
  },
  toast: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      title: "Changes saved",
      description: "Your profile has been updated.",
      variant: "success",
      state: "visible",
      speed: 1,
    },
  },
  "toggle-group": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      state: "Monthly",
      size: "default",
      speed: 1,
    },
  },
  tooltip: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      label: "Add to library",
      side: "top",
      state: "visible",
      speed: 1,
    },
  },
  "top-down-letters": {
    durationInFrames: 60,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "Signal",
      staggerDelay: 3,
      distance: 46,
      fontSize: 72,
      color: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "tracking-in": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "tracking in",
      startTracking: 0.5,
      startBlur: 12,
      fontSize: 96,
      color: "#171717",
      fontWeight: "700",
      speed: 1,
    },
  },
  "tv-power-off": {
    durationInFrames: 62,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#050505",
    },
    defaults: {
      durationInFrames: 18,
      gain: 1,
      afterglow: 1,
      phosphor: "#d8ecff",
      speed: 1,
    },
  },
  typewriter: {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    defaults: {
      text: "console.log('hello, world')",
      cursor: true,
      charsPerSecond: 22,
      fontSize: 72,
      color: "#171717",
      cursorColor: "#171717",
      fontWeight: "600",
      speed: 1,
    },
  },
  "typing-indicator": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "oklch(1 0 0)",
    },
    defaults: {
      dotCount: 3,
      size: 8,
      amplitude: 5,
      speed: 1,
    },
  },
  "underwater-ripple": {
    durationInFrames: 120,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#06171c",
    },
    defaults: {
      amplitude: 7,
      scale: 1,
      speed: 1,
      dispersion: 1,
    },
  },
  v0: {
    durationInFrames: 150,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#000000",
    },
    defaults: {
      greeting: "What do you want to create?",
      placeholder: "Ask v0 to build…",
      prompt: "a landing page for my SaaS with pricing and testimonials",
      modelName: "v0 Max",
      projectName: "Project",
      speed: 1,
    },
  },
  "value-swap": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      duration: 10,
      distance: 12,
      direction: "up",
      speed: 1,
    },
  },
  "vhs-filter": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#0a0a0a",
    },
    defaults: {
      bleed: 1,
      wobble: 1,
      noise: 1,
      intensity: 1,
      speed: 1,
    },
  },
  "warp-dissolve": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      distortion: 0.8,
      swirl: 0.6,
      softness: 1,
      speed: 1,
    },
  },
  "wave-wipe": {
    durationInFrames: 116,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      intensity: 0.2,
      softness: 0.7,
      noise: 0.4,
      colorBack: "#141318",
      speed: 1,
    },
  },
  "whip-pan": {
    durationInFrames: 114,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      direction: "left",
      blur: 24,
      speed: 1,
    },
  },
  "word-push": {
    durationInFrames: 90,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "move at your own pace",
      fontSize: 72,
      wordGap: 10,
      accel: 0.8,
      color: "#171717",
      fontWeight: "500",
      speed: 1,
    },
  },
  "word-stream": {
    durationInFrames: 100,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      text: "introducing | one-tap checkout | for your store",
      fontSize: 72,
      wordGap: 6,
      hold: 18,
      drift: 2,
      color: "#171717",
      fontWeight: "500",
      speed: 1,
    },
  },
  "x-follow-card": {
    durationInFrames: 165,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#f5f7f9",
    },
    defaults: {
      name: "remocn",
      handle: "remocn",
      bio: "Production-ready components for Remotion - text animations, backgrounds, transitions, UI blocks, and full scene compositions",
      avatarUrl: "/logo.svg",
      coverUrl: "/imgs/x-cover.png",
      location: "Ukraine",
      website: "remocn.dev",
      joined: "January 2024",
      verified: true,
      accentColor: "#1d9bf0",
      orientation: "horizontal",
      speed: 1,
    },
  },
  "x-followers-overview": {
    durationInFrames: 360,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#ffffff",
    },
    defaults: {
      totalFollowers: 1709,
      handle: "remocn",
      avatarUrl: "/logo.svg",
      accentColor: "#1d9bf0",
      orientation: "horizontal",
      speed: 1,
    },
  },
  "zoom-blur": {
    durationInFrames: 114,
    fps: 30,
    compositionWidth: 1280,
    compositionHeight: 720,
    previewBackdrop: {
      type: "color",
      value: "#141318",
    },
    defaults: {
      blur: 16,
      rise: 0,
      speed: 1,
    },
  },
};

export default previewManifest;
