import { scribbleCircleExampleCode } from "@/components/docs/examples/scribble-circle-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const scribbleCircleConfig: ComponentConfig = {
  componentName: "ScribbleCircle",
  importPath: "@/components/remocn/scribble-circle",
  controls: {
    laps: {
      type: "number",
      min: 0.5,
      max: 3,
      step: 0.05,
      default: 1.15,
      description: "Laps",
      hiddenFromList: false,
    },
    strokeWidth: {
      type: "number",
      min: 4,
      max: 32,
      step: 1,
      default: 14,
      description: "Brush width",
      hiddenFromList: false,
    },
    pressure: {
      type: "number",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 0.2,
      description: "Opening pressure",
      hiddenFromList: false,
    },
    grain: {
      type: "number",
      min: 0,
      max: 2,
      step: 0.1,
      default: 1,
      description: "Grain",
      hiddenFromList: false,
    },
    durationSteps: {
      type: "number",
      min: 2,
      max: 20,
      step: 1,
      default: 10,
      description: "Poses to draw",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#6f7f35",
      description: "Ink color",
    },
    seed: {
      type: "text-content",
      default: "scribble",
      description: "Seed",
    },
    step: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Frames / pose",
      hiddenFromList: false,
    },
  },
  snippet: scribbleCircleExampleCode,
  durationInFrames: 150,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
