import { displacementExampleCode } from "@/components/docs/examples/displacement-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const displacementConfig: ComponentConfig = {
  componentName: "displacement",
  importPath: "@/components/remocn/displacement",
  controls: {
    grid: {
      type: "number",
      min: 4,
      max: 100,
      step: 2,
      default: 60,
      description: "Grid",
      hiddenFromList: false,
    },
    cellAspect: {
      type: "number",
      min: 0.25,
      max: 4,
      step: 0.25,
      default: 1,
      description: "Cell aspect",
      hiddenFromList: false,
    },
    shift: {
      type: "number",
      min: 0,
      max: 4,
      step: 0.1,
      default: 1,
      description: "Shift",
      hiddenFromList: false,
    },
    aberration: {
      type: "number",
      min: 0,
      max: 3,
      step: 0.1,
      default: 1,
      description: "Aberration",
      hiddenFromList: false,
    },
    grain: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.5,
      description: "Grain",
      hiddenFromList: false,
    },
    stagger: {
      type: "number",
      min: 0,
      max: 0.85,
      step: 0.05,
      default: 0.45,
      description: "Stagger",
      hiddenFromList: false,
    },
  },
  durationInFrames: 72,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#0a0a0a" },
  snippet: displacementExampleCode,
};
