import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const perspectiveMarqueeConfig: ComponentConfig = {
  componentName: "PerspectiveMarquee",
  importPath: "@/components/remocn/perspective-marquee",
  controls: {
    fontSize: {
      type: "number",
      min: 24,
      max: 200,
      step: 2,
      default: 84,
      description: "Font size",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#fafafa",
      description: "Color",
    },
    fontWeight: {
      type: "enum",
      default: "700",
      variants: {
        "400": {},
        "500": {},
        "600": {},
        "700": {},
      },
      description: "Font weight",
    },
    pixelsPerFrame: {
      type: "number",
      min: 0.25,
      max: 10,
      step: 0.25,
      default: 2,
      description: "Pixels / frame",
      hiddenFromList: false,
    },
    rotateY: {
      type: "number",
      min: -60,
      max: 60,
      step: 1,
      default: -28,
      description: "Rotate Y (deg)",
      hiddenFromList: false,
    },
    rotateX: {
      type: "number",
      min: -30,
      max: 30,
      step: 1,
      default: 8,
      description: "Rotate X (deg)",
      hiddenFromList: false,
    },
    perspective: {
      type: "number",
      min: 400,
      max: 3000,
      step: 50,
      default: 1200,
      description: "Perspective",
      hiddenFromList: false,
    },
    fadeColor: {
      type: "color",
      default: "#050505",
      description: "Fade color",
    },
  },
  durationInFrames: 240,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#050505" },
};
