import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const fogRiseConfig: ComponentConfig = {
  componentName: "FogRise",
  importPath: "@/components/remocn/fog-rise",
  controls: {
    text: {
      type: "text-content",
      default: "Remocn",
      description: "Text",
    },
    fontSize: {
      type: "number",
      min: 40,
      max: 560,
      step: 4,
      default: 304,
      description: "Font size",
      hiddenFromList: false,
    },
    stagger: {
      type: "number",
      min: 0,
      max: 15,
      step: 1,
      default: 5,
      description: "Frames / ring",
      hiddenFromList: false,
    },
    blur: {
      type: "number",
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.17,
      description: "Blur (em)",
      hiddenFromList: false,
    },
    tilt: {
      type: "number",
      min: 0,
      max: 90,
      step: 5,
      default: 55,
      description: "Start tilt (deg)",
      hiddenFromList: false,
    },
    depth: {
      type: "number",
      min: 1,
      max: 8,
      step: 0.5,
      default: 5,
      description: "Perspective depth",
      hiddenFromList: false,
    },
    lift: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.85,
      description: "Lift (em)",
      hiddenFromList: false,
    },
    drift: {
      type: "number",
      min: 0,
      max: 0.012,
      step: 0.001,
      default: 0.005,
      description: "Drift (em / frame)",
      hiddenFromList: false,
    },
    exitAt: {
      type: "number",
      min: 0,
      max: 200,
      step: 5,
      default: 60,
      description: "Exit frame",
      hiddenFromList: false,
    },
    exitAccel: {
      type: "number",
      min: 0.002,
      max: 0.05,
      step: 0.002,
      default: 0.04,
      description: "Exit accel",
      hiddenFromList: false,
    },
    mass: {
      type: "number",
      min: 0.3,
      max: 3,
      step: 0.1,
      default: 1.3,
      description: "Mass",
      hiddenFromList: false,
    },
    stiffness: {
      type: "number",
      min: 30,
      max: 250,
      step: 10,
      default: 60,
      description: "Stiffness",
      hiddenFromList: false,
    },
    damping: {
      type: "number",
      min: 5,
      max: 30,
      step: 1,
      default: 13,
      description: "Damping",
      hiddenFromList: false,
    },
    spreadGap: {
      type: "number",
      min: 0,
      max: 0.3,
      step: 0.01,
      default: 0.07,
      description: "Spread gap (em)",
      hiddenFromList: false,
    },
    tracking: {
      type: "number",
      min: -0.12,
      max: 0,
      step: 0.005,
      default: -0.07,
      description: "Tracking (em)",
      hiddenFromList: false,
    },
    resolveFrames: {
      type: "number",
      min: 8,
      max: 50,
      step: 1,
      default: 22,
      description: "Converge frames",
      hiddenFromList: false,
    },
    fadeFrames: {
      type: "number",
      min: 2,
      max: 25,
      step: 1,
      default: 18,
      description: "Fade frames",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#004CFF",
      description: "Color",
    },
    fontWeight: {
      type: "enum",
      default: "400",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },

  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#ffffff" },
};
