import { crumpleTossExampleCode } from "@/components/docs/examples/crumple-toss-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const crumpleTossConfig: ComponentConfig = {
  componentName: "CrumpleToss",
  importPath: "@/components/remocn/crumple-toss",
  controls: {
    at: {
      type: "number",
      min: 0,
      max: 24,
      step: 3,
      default: 6,
      description: "Crumple starts",
      hiddenFromList: false,
    },
    crumpleSteps: {
      type: "number",
      min: 2,
      max: 8,
      step: 1,
      default: 4,
      description: "Crush poses",
      hiddenFromList: false,
    },
    tossSteps: {
      type: "number",
      min: 2,
      max: 10,
      step: 1,
      default: 5,
      description: "Flight poses",
      hiddenFromList: false,
    },
    direction: {
      type: "number",
      min: -180,
      max: 180,
      step: 5,
      default: -35,
      description: "Throw angle",
      hiddenFromList: false,
    },
    distance: {
      type: "number",
      min: 200,
      max: 1600,
      step: 20,
      default: 440,
      description: "Arc scale",
      hiddenFromList: false,
    },
    spin: {
      type: "number",
      min: 0,
      max: 720,
      step: 10,
      default: 220,
      description: "Tumble",
      hiddenFromList: false,
    },
    segments: {
      type: "number",
      min: 5,
      max: 14,
      step: 1,
      default: 9,
      description: "Paper segments",
      hiddenFromList: false,
    },
    layers: {
      type: "number",
      min: 1,
      max: 3,
      step: 1,
      default: 2,
      description: "Fold layers",
      hiddenFromList: false,
    },
    randomness: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.6,
      description: "Fold randomness",
      hiddenFromList: false,
    },
    crushTo: {
      type: "number",
      min: 0.15,
      max: 0.7,
      step: 0.01,
      default: 0.34,
      description: "Wad size",
      hiddenFromList: false,
    },
    seed: {
      type: "text-content",
      default: "toss",
      description: "Seed",
    },
    step: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Frames / pose",
      hiddenFromList: false,
    },
  },
  snippet: crumpleTossExampleCode,
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
