import { crumpleTossExampleCode } from "@/components/docs/examples/crumple-toss-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const crumpleTossConfig: ComponentConfig = {
  componentName: "CrumpleToss",
  importPath: "@/components/remocn/crumple-toss",
  controls: {
    at: {
      type: "number",
      default: 6,
      min: 0,
      max: 24,
      step: 3,
      label: "Crumple starts",
    },
    crumpleSteps: {
      type: "number",
      default: 4,
      min: 2,
      max: 8,
      step: 1,
      label: "Crush poses",
    },
    tossSteps: {
      type: "number",
      default: 5,
      min: 2,
      max: 10,
      step: 1,
      label: "Flight poses",
    },
    direction: {
      type: "number",
      default: -35,
      min: -180,
      max: 180,
      step: 5,
      label: "Throw angle",
    },
    distance: {
      type: "number",
      default: 440,
      min: 200,
      max: 1600,
      step: 20,
      label: "Arc scale",
    },
    spin: {
      type: "number",
      default: 220,
      min: 0,
      max: 720,
      step: 10,
      label: "Tumble",
    },
    segments: {
      type: "number",
      default: 9,
      min: 5,
      max: 14,
      step: 1,
      label: "Paper segments",
    },
    layers: {
      type: "number",
      default: 2,
      min: 1,
      max: 3,
      step: 1,
      label: "Fold layers",
    },
    randomness: {
      type: "number",
      default: 0.6,
      min: 0,
      max: 1,
      step: 0.05,
      label: "Fold randomness",
    },
    crushTo: {
      type: "number",
      default: 0.34,
      min: 0.15,
      max: 0.7,
      step: 0.01,
      label: "Wad size",
    },
    seed: { type: "text", default: "toss", label: "Seed" },
    step: {
      type: "number",
      default: 3,
      min: 1,
      max: 6,
      step: 1,
      label: "Frames / pose",
    },
  },
  snippet: crumpleTossExampleCode,
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
