import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const shaderLightTunnelConfig: ComponentConfig = {
  componentName: "ShaderLightTunnel",
  importPath: "@/components/remocn/shader-light-tunnel",
  controls: {
    speed: {
      type: "number",
      default: 1,
      min: 0,
      max: 5,
      step: 0.1,
      description: "Flight speed",
      hiddenFromList: false,
    },
    twist: {
      type: "number",
      default: 0.7,
      min: 0,
      max: 2,
      step: 0.05,
      description: "Spiral motion",
      hiddenFromList: false,
    },
    spirals: {
      type: "number",
      default: 3,
      min: 1,
      max: 6,
      step: 1,
      description: "Spiral count",
      hiddenFromList: false,
    },
    glow: {
      type: "number",
      default: 1,
      min: 0,
      max: 3,
      step: 0.05,
      description: "Light exposure",
      hiddenFromList: false,
    },
    depth: {
      type: "number",
      default: 1,
      min: 0.5,
      max: 2,
      step: 0.05,
      description: "Perspective",
      hiddenFromList: false,
    },
    timeOffset: {
      type: "number",
      default: 0,
      min: 0,
      max: 60,
      step: 0.1,
      description: "Start time",
      hiddenFromList: false,
    },
  },
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#05050a" },
};
