import { zColor } from "@remotion/zod-types";
import { z } from "zod";

const progress = z.number().min(0).max(1).step(0.001);
const position = z.number().min(-2000).max(2000).step(1);
const size = z.number().min(0).max(2400).step(1);
const scale = z.number().min(0).max(5).step(0.001);
const angle = z.number().min(-180).max(180).step(1);
const fontSize = z.number().min(8).max(400).step(1);

export const introducingProductEasingSchema = z.enum([
  "linear",
  "ease-in",
  "ease-out",
  "ease-in-out",
  "snappy",
  "smooth",
  "spring",
]);

const featureSchema = z.object({
  eyebrow: z.string(),
  title: z.string(),
  description: z.string(),
  stat: z.string(),
});

const timelineSchema = z.object({
  speed: z.number().min(0.25).max(4).step(0.05),
  hook: z.number().int().min(12).max(1800),
  command: z.number().int().min(12).max(1800),
  brand: z.number().int().min(12).max(1800),
  productUi: z.number().int().min(12).max(1800),
  speedScene: z.number().int().min(12).max(1800),
  features: z.number().int().min(12).max(1800),
  montage: z.number().int().min(12).max(1800),
  learningLoop: z.number().int().min(12).max(1800),
  topics: z.number().int().min(12).max(1800),
  outro: z.number().int().min(12).max(1800),
});

const commonMotion = {
  x: position,
  y: position,
  fadeInEnd: progress,
  fadeOutStart: progress,
  easing: introducingProductEasingSchema,
};

export const introducingProductSchema = z.object({
  content: z.object({
    productName: z.string(),
    tagline: z.string(),
    hookLine: z.string(),
    contrastLine: z.string(),
    command: z.string(),
    benefit: z.string(),
    metric: z.string(),
    montageTitle: z.string(),
    topicIntro: z.string(),
    loopWords: z.array(z.string()).min(1).max(8),
    featureCards: z.array(featureSchema).min(1).max(6),
    topics: z.array(z.string()).min(1).max(8),
    logoUrl: z.string(),
    screenshotUrls: z.array(z.string()).max(6),
  }),
  theme: z.object({
    darkBackground: zColor(),
    lightBackground: zColor(),
    darkText: zColor(),
    lightText: zColor(),
    darkMutedText: zColor(),
    lightMutedText: zColor(),
    accentColor: zColor(),
    warmColor: zColor(),
    fontFamily: z.string(),
    canvasScale: scale,
    gridSize: size,
    gridOpacity: z.number().min(0).max(1).step(0.01),
    glowBlur: size,
    glowOpacity: z.number().min(0).max(1).step(0.01),
    windowBackground: zColor(),
    windowBorderColor: zColor(),
    windowWidth: size,
    windowHeight: size,
    compactWindowWidth: size,
    compactWindowHeight: size,
    windowRadius: size,
  }),
  timeline: timelineSchema,
  scenes: z.object({
    hook: z.object({
      ...commonMotion,
      secondBeatAt: progress,
      startFontSize: fontSize,
      enterFontSize: fontSize,
      settleFontSize: fontSize,
      fontWeight: z.number().int().min(100).max(900),
      letterSpacing: z.number().min(-0.2).max(0.2).step(0.005),
      blur: size,
      enterOffsetX: position,
    }),
    command: z.object({
      ...commonMotion,
      collapsedWidth: size,
      expandedWidth: size,
      height: size,
      paddingX: size,
      fontSize,
      fontWeight: z.number().int().min(100).max(900),
      expandEnd: progress,
      typeStart: progress,
      typeEnd: progress,
      cursorX: position,
      cursorY: position,
      cursorWidth: size,
      cursorHeight: size,
    }),
    brand: z.object({
      ...commonMotion,
      logoSize: size,
      startScale: scale,
      endScale: scale,
      settleAt: progress,
    }),
    productUi: z.object({
      ...commonMotion,
      startY: position,
      endY: position,
      startScale: scale,
      endScale: scale,
      startRotateX: angle,
      endRotateX: angle,
      startRotateY: angle,
      endRotateY: angle,
      settleAt: progress,
    }),
    speed: z.object({
      ...commonMotion,
      introFontSize: fontSize,
      metricFontSize: fontSize,
      introOutAt: progress,
      metricInAt: progress,
      countStart: progress,
      countEnd: progress,
      pillWidth: size,
      pillHeight: size,
      pillScale: z.array(scale).length(4),
    }),
    features: z.object({
      ...commonMotion,
      beatGap: progress,
      cardLifetime: progress,
      enterXEven: position,
      enterXOdd: position,
      centerX: position,
      exitXEven: position,
      exitXOdd: position,
      startY: position,
      endY: position,
      startScale: scale,
      peakScale: scale,
      endScale: scale,
      startRotateX: angle,
      peakRotateX: angle,
      endRotateX: angle,
      startRotateY: angle,
      endRotateY: angle,
      taglineX: position,
      taglineBottom: position,
      taglineFontSize: fontSize,
    }),
    montage: z.object({
      ...commonMotion,
      titleY: position,
      titleFontSize: fontSize,
      cardScale: scale,
      spreadStart: scale,
      spreadEnd: progress,
      cards: z
        .array(
          z.object({
            x: position,
            y: position,
            rotate: angle,
          }),
        )
        .length(3),
    }),
    learningLoop: z.object({
      ...commonMotion,
      startOrbSize: size,
      endOrbSize: size,
      orbScale: scale,
      orbitSpeed: z.number().min(-0.2).max(0.2).step(0.001),
      benefitFontSize: fontSize,
      benefitOutAt: progress,
      wordsInAt: progress,
      wordsFontSize: fontSize,
      wordsGap: size,
      highlightStart: progress,
      highlightStep: z.number().min(1).max(120).step(1),
      blur: size,
    }),
    topics: z.object({
      ...commonMotion,
      introFontSize: fontSize,
      topicStartAt: progress,
      topicStartSize: fontSize,
      topicEndSize: fontSize,
      topicBlur: size,
      topicFontWeight: z.number().int().min(100).max(900),
    }),
    outro: z.object({
      ...commonMotion,
      logoSize: size,
      startScale: scale,
      settleAt: progress,
      nameRevealAt: progress,
      taglineBottom: position,
      taglineFontSize: fontSize,
      orbitSpeed: z.number().min(-0.2).max(0.2).step(0.001),
      orbitVerticalScale: scale,
      orbits: z
        .array(
          z.object({
            radius: size,
            phase: z.number().min(-12).max(12).step(0.1),
            size,
          }),
        )
        .length(3),
      rings: z.array(size).length(3),
    }),
  }),
  className: z.string(),
});

export type IntroducingProductStudioProps = z.infer<
  typeof introducingProductSchema
>;

export const DEFAULT_INTRODUCING_PRODUCT_PROPS: IntroducingProductStudioProps =
  {
    content: {
      productName: "Northstar",
      tagline: "Turn complexity into forward motion.",
      hookLine: "Become the builder",
      contrastLine: "AI cannot replace",
      command: "/show me how the product really works",
      benefit: "Move beyond limits",
      metric: "10× faster",
      montageTitle: "One system for forward motion",
      topicIntro: "Learn all of it",
      loopWords: ["create", "learn", "share", "grow", "repeat"],
      featureCards: [
        {
          eyebrow: "Workspace",
          title: "One place for the whole product story",
          description:
            "Keep research, decisions, and progress in a shared view.",
          stat: "12 active projects",
        },
        {
          eyebrow: "Signals",
          title: "See momentum while it happens",
          description:
            "Turn activity into a clear picture of what matters next.",
          stat: "+46% this week",
        },
        {
          eyebrow: "Knowledge",
          title: "Go from detail to understanding",
          description:
            "Connect notes, examples, and context without losing focus.",
          stat: "9× faster",
        },
      ],
      topics: [
        "Product strategy",
        "Customer insights",
        "Launch systems",
        "Team workflows",
        "Your next idea",
      ],
      logoUrl: "",
      screenshotUrls: [],
    },
    theme: {
      darkBackground: "#050507",
      lightBackground: "#fbfaff",
      darkText: "#f8f7fb",
      lightText: "#111014",
      darkMutedText: "#8e8c98",
      lightMutedText: "#625f69",
      accentColor: "#6d3cff",
      warmColor: "#ff7a33",
      fontFamily:
        "var(--font-geist-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
      canvasScale: 1.001,
      gridSize: 120,
      gridOpacity: 0.12,
      glowBlur: 92,
      glowOpacity: 0.72,
      windowBackground: "#0d0d11",
      windowBorderColor: "#ffffff38",
      windowWidth: 920,
      windowHeight: 520,
      compactWindowWidth: 560,
      compactWindowHeight: 330,
      windowRadius: 30,
    },
    timeline: {
      speed: 1,
      hook: 126,
      command: 90,
      brand: 42,
      productUi: 126,
      speedScene: 99,
      features: 507,
      montage: 78,
      learningLoop: 192,
      topics: 126,
      outro: 210,
    },
    scenes: {
      hook: {
        x: 0,
        y: 0,
        fadeInEnd: 0.07,
        fadeOutStart: 0.43,
        easing: "smooth",
        secondBeatAt: 0.524,
        startFontSize: 290,
        enterFontSize: 74,
        settleFontSize: 64,
        fontWeight: 650,
        letterSpacing: -0.065,
        blur: 13,
        enterOffsetX: 120,
      },
      command: {
        x: 0,
        y: -14,
        fadeInEnd: 0.12,
        fadeOutStart: 0.91,
        easing: "smooth",
        collapsedWidth: 120,
        expandedWidth: 760,
        height: 110,
        paddingX: 38,
        fontSize: 37,
        fontWeight: 560,
        expandEnd: 0.33,
        typeStart: 0.17,
        typeEnd: 0.69,
        cursorX: 346,
        cursorY: 86,
        cursorWidth: 48,
        cursorHeight: 60,
      },
      brand: {
        x: 0,
        y: 0,
        fadeInEnd: 0.24,
        fadeOutStart: 0.81,
        easing: "smooth",
        logoSize: 104,
        startScale: 0.72,
        endScale: 1,
        settleAt: 0.57,
      },
      productUi: {
        x: 0,
        y: 29,
        fadeInEnd: 0.14,
        fadeOutStart: 0.86,
        easing: "smooth",
        startY: 120,
        endY: -40,
        startScale: 0.72,
        endScale: 1.02,
        startRotateX: 18,
        endRotateX: 7,
        startRotateY: -17,
        endRotateY: -6,
        settleAt: 0.67,
      },
      speed: {
        x: 0,
        y: 0,
        fadeInEnd: 0.12,
        fadeOutStart: 0.91,
        easing: "ease-out",
        introFontSize: 62,
        metricFontSize: 44,
        introOutAt: 0.42,
        metricInAt: 0.34,
        countStart: 0.4,
        countEnd: 0.67,
        pillWidth: 360,
        pillHeight: 150,
        pillScale: [3.1, 2.35, 1.62, 1],
      },
      features: {
        x: 0,
        y: 14,
        fadeInEnd: 0.04,
        fadeOutStart: 0.94,
        easing: "smooth",
        beatGap: 0.316,
        cardLifetime: 0.398,
        enterXEven: -860,
        enterXOdd: 220,
        centerX: -460,
        exitXEven: -920,
        exitXOdd: 250,
        startY: 40,
        endY: -70,
        startScale: 0.76,
        peakScale: 1.06,
        endScale: 1.18,
        startRotateX: 13,
        peakRotateX: 4,
        endRotateX: -7,
        startRotateY: -13,
        endRotateY: 7,
        taglineX: 74,
        taglineBottom: 62,
        taglineFontSize: 18,
      },
      montage: {
        x: 0,
        y: 0,
        fadeInEnd: 0.23,
        fadeOutStart: 0.85,
        easing: "smooth",
        titleY: 52,
        titleFontSize: 34,
        cardScale: 0.58,
        spreadStart: 1.35,
        spreadEnd: 0.62,
        cards: [
          { x: -450, y: -170, rotate: -9 },
          { x: 80, y: -225, rotate: 7 },
          { x: -90, y: 125, rotate: -2 },
        ],
      },
      learningLoop: {
        x: 0,
        y: 0,
        fadeInEnd: 0.09,
        fadeOutStart: 0.88,
        easing: "smooth",
        startOrbSize: 210,
        endOrbSize: 330,
        orbScale: 0.68,
        orbitSpeed: 0.032,
        benefitFontSize: 57,
        benefitOutAt: 0.52,
        wordsInAt: 0.48,
        wordsFontSize: 29,
        wordsGap: 22,
        highlightStart: 0.55,
        highlightStep: 14,
        blur: 18,
      },
      topics: {
        x: 0,
        y: 0,
        fadeInEnd: 0.08,
        fadeOutStart: 0.92,
        easing: "smooth",
        introFontSize: 64,
        topicStartAt: 0.3,
        topicStartSize: 150,
        topicEndSize: 84,
        topicBlur: 12,
        topicFontWeight: 620,
      },
      outro: {
        x: 0,
        y: -7,
        fadeInEnd: 0.16,
        fadeOutStart: 0.94,
        easing: "smooth",
        logoSize: 118,
        startScale: 0.58,
        settleAt: 0.33,
        nameRevealAt: 0.5,
        taglineBottom: 145,
        taglineFontSize: 19,
        orbitSpeed: 0.012,
        orbitVerticalScale: 0.38,
        orbits: [
          { radius: 260, phase: 0, size: 48 },
          { radius: 355, phase: 2.2, size: 32 },
          { radius: 440, phase: 4.1, size: 58 },
        ],
        rings: [250, 360, 475],
      },
    },
    className: "",
  };
