import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const typedSplitWipeConfig: ComponentConfig = {
  componentName: "TypedSplitWipe",
  importPath: "@/components/remocn/typed-split-wipe",
  controls: {
    prefix: {
      type: "text-content",
      default: "Introducing",
      description: "Leading text",
    },
    anchor: {
      type: "text-content",
      default: "X",
      description: "Persistent anchor",
    },
    suffix: {
      type: "text-content",
      default: "Ads MCP",
      description: "Staggered trailing words",
    },
    typeFrames: {
      type: "number",
      min: 6,
      max: 60,
      step: 1,
      default: 30,
      description: "Typing frames",
      hiddenFromList: false,
    },
    exitAt: {
      type: "number",
      min: 20,
      max: 90,
      step: 1,
      default: 50,
      description: "Exit start frame",
      hiddenFromList: false,
    },
    exitFrames: {
      type: "number",
      min: 6,
      max: 40,
      step: 1,
      default: 20,
      description: "Exit duration",
      hiddenFromList: false,
    },
    wordStagger: {
      type: "number",
      min: 0,
      max: 12,
      step: 1,
      default: 4,
      description: "Suffix word stagger",
      hiddenFromList: false,
    },
    anchorShift: {
      type: "number",
      min: -200,
      max: 0,
      step: 2,
      default: -72,
      description: "Anchor exit shift",
      hiddenFromList: false,
    },
    fontSize: {
      type: "number",
      min: 18,
      max: 120,
      step: 1,
      default: 42,
      description: "Font size",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#e8e8e8",
      description: "Text color",
    },
    fontWeight: {
      type: "enum",
      default: "400",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },
  durationInFrames: 75,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#101010" },
};
