import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const gradientScaleCutTextConfig: ComponentConfig = {
  componentName: "GradientScaleCutText",
  importPath: "@/components/remocn/gradient-scale-cut-text",
  controls: {
    text: {
      type: "text-content",
      default: "Introducing",
      description: "Text",
    },
    giantFontSize: {
      type: "number",
      min: 160,
      max: 720,
      step: 4,
      default: 520,
      description: "Giant font size",
      hiddenFromList: false,
    },
    compactFontSize: {
      type: "number",
      min: 40,
      max: 240,
      step: 2,
      default: 132,
      description: "Compact font size",
      hiddenFromList: false,
    },
    anchorOffsetX: {
      type: "number",
      min: -400,
      max: 400,
      step: 4,
      default: -16,
      description: "Final horizontal anchor offset",
      hiddenFromList: false,
    },
    giantTravel: {
      type: "number",
      min: 0,
      max: 800,
      step: 4,
      default: 400,
      description: "Giant phase left travel",
      hiddenFromList: false,
    },
    settleTravel: {
      type: "number",
      min: 0,
      max: 400,
      step: 4,
      default: 160,
      description: "Compact phase left travel",
      hiddenFromList: false,
    },
    cutFrame: {
      type: "number",
      min: 4,
      max: 24,
      step: 1,
      default: 13,
      description: "Hard cut frame",
      hiddenFromList: false,
    },
    revealSoftness: {
      type: "number",
      min: 0,
      max: 40,
      step: 1,
      default: 14,
      description: "Reveal edge softness",
      hiddenFromList: false,
    },
    compactBlur: {
      type: "number",
      min: 0,
      max: 40,
      step: 1,
      default: 12,
      description: "Blur after the cut",
      hiddenFromList: false,
    },
    gradientStart: {
      type: "color",
      default: "#f04a14",
      description: "Gradient start",
    },
    gradientEnd: {
      type: "color",
      default: "#f3f1f1",
      description: "Gradient end",
    },
    ghostColor: {
      type: "color",
      default: "#170b0a",
      description: "Unrevealed text color",
    },
    backgroundColor: {
      type: "color",
      default: "#000000",
      description: "Background color",
    },
    fontWeight: {
      type: "enum",
      default: "700",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },
  durationInFrames: 36,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#000000" },
};
