import { shaderSpiralPassExampleCode } from "@/components/docs/examples/shader-spiral-pass-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const shaderSpiralPassConfig: ComponentConfig = {
  componentName: "shaderSpiralPass",
  importPath: "@/components/remocn/shader-spiral-pass",
  controls: {
    speed: {
      type: "number",
      default: 1,
      min: 0,
      max: 5,
      step: 0.1,
      description: "Shader flow speed",
      hiddenFromList: false,
    },
    spirals: {
      type: "number",
      default: 3,
      min: 1,
      max: 6,
      step: 1,
      description: "Spiral count",
      hiddenFromList: false,
    },
    twist: {
      type: "number",
      default: 0.7,
      min: 0,
      max: 2,
      step: 0.05,
      description: "Spiral motion",
      hiddenFromList: false,
    },
    zoom: {
      type: "number",
      default: 14,
      min: 2,
      max: 24,
      step: 1,
      description: "Camera push",
      hiddenFromList: false,
    },
    softness: {
      type: "number",
      default: 0.12,
      min: 0.02,
      max: 0.3,
      step: 0.01,
      description: "Exit softness",
      hiddenFromList: false,
    },
    timeOffset: {
      type: "number",
      default: 0,
      min: 0,
      max: 60,
      step: 0.1,
      description: "Start time",
      hiddenFromList: false,
    },
  },
  durationInFrames: 168,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#15111c" },
  snippet: shaderSpiralPassExampleCode,
};
