import {
  type ComponentConfig,
  enumVariants,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const echoStackConfig: ComponentConfig = {
  componentName: "EchoStack",
  importPath: "@/components/remocn/echo-stack",
  controls: {
    text: { type: "text-content", default: "Bold.", description: "Text" },
    color: { type: "color", default: "#fafafa", description: "Text color" },
    echoColor: { type: "color", default: "#fafafa", description: "Echo color" },
    direction: {
      type: "enum",
      default: "up",
      variants: enumVariants(["up", "down"]),
      description: "Direction",
    },
    fontSize: {
      type: "number",
      default: 170,
      min: 60,
      max: 300,
      step: 2,
      description: "Font size",
      hiddenFromList: false,
    },
    echoes: {
      type: "number",
      default: 3,
      min: 1,
      max: 6,
      step: 1,
      description: "Echoes per side",
      hiddenFromList: false,
    },
    echoOpacity: {
      type: "number",
      default: 0.35,
      min: 0.05,
      max: 1,
      step: 0.05,
      description: "Echo opacity",
      hiddenFromList: false,
    },
    cycle: {
      type: "number",
      default: 60,
      min: 15,
      max: 240,
      step: 5,
      description: "Frames per row",
      hiddenFromList: false,
    },
  },
  durationInFrames: 120,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#0a0a0a" },
};
