import { inkArrowExampleCode } from "@/components/docs/examples/ink-arrow-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const inkArrowConfig: ComponentConfig = {
  componentName: "InkArrow",
  importPath: "@/components/remocn/ink-arrow",
  controls: {
    curvature: {
      type: "number",
      min: -1,
      max: 1,
      step: 0.05,
      default: 0.35,
      description: "Curvature",
      hiddenFromList: false,
    },
    strokeWidth: {
      type: "number",
      min: 2,
      max: 24,
      step: 1,
      default: 8,
      description: "Brush width",
      hiddenFromList: false,
    },
    pressure: {
      type: "number",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 0.2,
      description: "Opening pressure",
      hiddenFromList: false,
    },
    release: {
      type: "number",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 1,
      description: "Closing pressure",
      hiddenFromList: false,
    },
    grain: {
      type: "number",
      min: 0,
      max: 2,
      step: 0.1,
      default: 1,
      description: "Grain",
      hiddenFromList: false,
    },
    headSize: {
      type: "number",
      min: 8,
      max: 48,
      step: 1,
      default: 24,
      description: "Head size",
      hiddenFromList: false,
    },
    drawDur: {
      type: "number",
      min: 12,
      max: 90,
      step: 1,
      default: 36,
      description: "Draw frames",
      hiddenFromList: false,
    },
    headDur: {
      type: "number",
      min: 4,
      max: 48,
      step: 1,
      default: 12,
      description: "Head frames",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#26242c",
      description: "Ink color",
    },
    seed: {
      type: "text-content",
      default: "arrow",
      description: "Seed",
    },
    step: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Frames / pose",
      hiddenFromList: false,
    },
  },
  snippet: inkArrowExampleCode,
  durationInFrames: 150,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
