import { stageExampleCode } from "@/components/docs/examples/stage-example";
import {
  type ComponentConfig,
  enumVariants,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const stageConfig: ComponentConfig = {
  componentName: "Stage",
  importPath: "@/components/remocn/stage",
  controls: {
    preset: {
      type: "enum",
      default: "smooth-descent",
      variants: enumVariants([
        "smooth-descent",
        "site-tour",
        "hero-push",
        "section-hop",
      ]),
      description: "Camera path",
    },
    shake: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0,
      description: "Handheld shake",
      hiddenFromList: false,
    },
    seed: {
      type: "text-content",
      default: "remocn-smooth-descent",
      description: "Shake seed",
    },
    backdrop: {
      type: "text-content",
      default: "linear-gradient(145deg, #17181d 0%, #09090b 72%)",
      description: "Backdrop (CSS)",
    },
    rotateX: {
      type: "number",
      min: -180,
      max: 180,
      step: 1,
      default: 14,
      description: "Rotate X",
      hiddenFromList: false,
    },
    rotateY: {
      type: "number",
      min: -180,
      max: 180,
      step: 1,
      default: -20,
      description: "Rotate Y",
      hiddenFromList: false,
    },
    perspective: {
      type: "number",
      min: 50,
      max: 5000,
      step: 25,
      default: 900,
      description: "Perspective",
      hiddenFromList: false,
    },
    scale: {
      type: "number",
      min: 0.1,
      max: 3,
      step: 0.01,
      default: 0.86,
      description: "Scale",
      hiddenFromList: false,
    },
    radius: {
      type: "number",
      min: 0,
      max: 4,
      step: 0.1,
      default: 1.4,
      description: "Radius",
      hiddenFromList: false,
    },
    reflection: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.24,
      description: "Reflection",
      hiddenFromList: false,
    },
    shadow: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.7,
      description: "Contact shadow",
      hiddenFromList: false,
    },
    light: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.55,
      description: "Studio light",
      hiddenFromList: false,
    },
  },
  durationInFrames: 300,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  snippet: stageExampleCode,
};
