import { stageExampleCode } from "@/components/docs/examples/stage-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const stageConfig: ComponentConfig = {
  componentName: "Stage",
  importPath: "@/components/remocn/stage",
  controls: {
    backdrop: {
      type: "text-content",
      default: "linear-gradient(145deg, #17181d 0%, #09090b 72%)",
      description: "Backdrop (CSS)",
    },
    rotateX: {
      type: "number",
      min: -24,
      max: 24,
      step: 1,
      default: 8,
      description: "Rotate X",
      hiddenFromList: false,
    },
    rotateY: {
      type: "number",
      min: -30,
      max: 30,
      step: 1,
      default: -12,
      description: "Rotate Y",
      hiddenFromList: false,
    },
    perspective: {
      type: "number",
      min: 500,
      max: 3000,
      step: 50,
      default: 1400,
      description: "Perspective",
      hiddenFromList: false,
    },
    scale: {
      type: "number",
      min: 0.5,
      max: 1,
      step: 0.01,
      default: 0.82,
      description: "Scale",
      hiddenFromList: false,
    },
    radius: {
      type: "number",
      min: 0,
      max: 4,
      step: 0.1,
      default: 1.4,
      description: "Radius",
      hiddenFromList: false,
    },
    reflection: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.24,
      description: "Reflection",
      hiddenFromList: false,
    },
    shadow: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.7,
      description: "Contact shadow",
      hiddenFromList: false,
    },
    light: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.55,
      description: "Studio light",
      hiddenFromList: false,
    },
  },
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  snippet: stageExampleCode,
};
