import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const ringTextConfig: ComponentConfig = {
  componentName: "RingText",
  importPath: "@/components/remocn/ring-text",
  controls: {
    text: {
      type: "text-content",
      default: "Type in motion",
      description: "Text",
    },
    separator: {
      type: "text-content",
      default: "•",
      description: "Separator",
    },
    color: { type: "color", default: "#d4ff1f", description: "Text color" },
    band: { type: "color", default: "#0a0a0a", description: "Band color" },
    radius: {
      type: "number",
      default: 210,
      min: 80,
      max: 340,
      step: 5,
      description: "Radius",
      hiddenFromList: false,
    },
    fontSize: {
      type: "number",
      default: 40,
      min: 16,
      max: 90,
      step: 1,
      description: "Font size",
      hiddenFromList: false,
    },
    tilt: {
      type: "number",
      default: 38,
      min: 0,
      max: 80,
      step: 1,
      description: "Tilt",
      hiddenFromList: false,
    },
    roll: {
      type: "number",
      default: -16,
      min: -60,
      max: 60,
      step: 1,
      description: "Roll",
      hiddenFromList: false,
    },
    period: {
      type: "number",
      default: 240,
      min: 60,
      max: 900,
      step: 10,
      description: "Frames per turn",
      hiddenFromList: false,
    },
  },
  durationInFrames: 180,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#d4ff1f" },
};
