import { readFileSync, writeFileSync } from "node:fs";

// This follows the existing templates' self-contained registry asset convention.
// Preserve the public media keys while replacing every default plate.
const names = [
  ["desk", "workbench"],
  ["horizon", "gallery"],
  ["rocket", "sculpture"],
  ["earth", "courtyard"],
] as const;
const media = Object.fromEntries(
  names.map(([key, name]) => [
    key,
    `data:image/jpeg;base64,${readFileSync(`public/templates/product-showcase/${name}.jpg`).toString("base64")}`,
  ]),
);
writeFileSync(
  "registry/remocn-templates/launch-anything/assets.ts",
  `// GENERATED by bun scripts/build-launch-assets.mts. Original AI-generated editorial plates.\n// Asset prompts and provenance: docs/plans/2026-09-10-product-showcase-assets.md.\nexport const launchMedia = ${JSON.stringify(media, null, 2)};\n`,
);
console.log(`Bundled ${names.length} launch-anything images.`);
