import { readFileSync, writeFileSync } from "node:fs";

const names = ["ceramics", "materials", "chair"] as const;
const media = Object.fromEntries(
  names.map((name) => [
    name,
    `data:image/jpeg;base64,${readFileSync(`public/templates/brand-guidelines/${name}.jpg`).toString("base64")}`,
  ]),
);
writeFileSync(
  "registry/remocn-templates/brand-guidelines/assets.ts",
  `// GENERATED by bun scripts/build-brand-guidelines-assets.mts.\n// Original AI-generated still-life photographs; no source-video assets.\n// Prompts and provenance: docs/plans/2026-09-10-brand-guidelines-assets.md.\nexport const brandGuidelinesMedia = ${JSON.stringify(media, null, 2)};\n`,
);
console.log(`Bundled ${names.length} Brand Guidelines photographs.`);
