import { readFileSync, writeFileSync } from "node:fs";

// This follows the existing templates' self-contained registry asset convention.
const names = ["desk", "horizon", "rocket", "earth"] as const;
const media = Object.fromEntries(
  names.map((name) => [
    name,
    `data:image/jpeg;base64,${readFileSync(`public/templates/launch-anything/${name}.jpg`).toString("base64")}`,
  ]),
);
writeFileSync(
  "registry/remocn-templates/launch-anything/assets.ts",
  `// GENERATED by bun scripts/build-launch-assets.mts. AI-reconstructed photographic plates.\n// Asset prompts and provenance: docs/plans/2026-09-10-launch-anything-design.md.\nexport const launchMedia = ${JSON.stringify(media, null, 2)};\n`,
);
console.log(`Bundled ${names.length} launch-anything images.`);
