import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";
import { getRadialBurstDuration } from ".";

export const radialBurstConfig: ComponentConfig = {
  componentName: "RadialBurst",
  importPath: "@/components/remocn/radial-burst",
  controls: {
    segments: {
      type: "number",
      default: 8,
      min: 4,
      max: 16,
      step: 1,
      description: "Segments",
      hiddenFromList: false,
    },
    radius: {
      type: "number",
      default: 210,
      min: 100,
      max: 280,
      step: 5,
      description: "Burst radius",
      hiddenFromList: false,
    },
    thickness: {
      type: "number",
      default: 30,
      min: 8,
      max: 60,
      step: 1,
      description: "Thickness",
      hiddenFromList: false,
    },
    rotation: {
      type: "number",
      default: 135,
      min: -360,
      max: 360,
      step: 15,
      description: "Rotation",
      hiddenFromList: false,
    },
    intensity: {
      type: "number",
      default: 1,
      min: 0,
      max: 1.5,
      step: 0.1,
      description: "Intensity",
      hiddenFromList: false,
    },
    twist: {
      type: "number",
      default: 110,
      min: -180,
      max: 180,
      step: 10,
      description: "Ribbon twist",
      hiddenFromList: false,
    },
    echoes: {
      type: "number",
      default: 3,
      min: 0,
      max: 5,
      step: 1,
      description: "Contour echoes",
      hiddenFromList: false,
    },
    color: { type: "color", default: "#ffffff", description: "Shape color" },
    accentColor: {
      type: "color",
      default: "#f4e4a7",
      description: "Accent color",
    },
    backgroundColor: {
      type: "color",
      default: "#a800b7",
      description: "Background",
    },
    loop: { type: "boolean", default: false, description: "Loop animation" },
  },
  durationInFrames: 120,
  getDurationInFrames: (values) => getRadialBurstDuration(values),
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
};
