import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const handCountConfig: ComponentConfig = {
  componentName: "HandCount",
  importPath: "@/components/remocn/hand-count",
  controls: {
    to: {
      type: "number",
      default: 1284,
      min: 0,
      max: 10000,
      step: 1,
      label: "Count to",
    },
    from: {
      type: "number",
      default: 0,
      min: 0,
      max: 1000,
      step: 1,
      label: "Count from",
    },
    durationSteps: {
      type: "number",
      default: 18,
      min: 2,
      max: 24,
      step: 1,
      label: "Poses counting",
    },
    decimals: {
      type: "number",
      default: 0,
      min: 0,
      max: 2,
      step: 1,
      label: "Decimals",
    },
    prefix: { type: "text", default: "", label: "Prefix" },
    suffix: { type: "text", default: "", label: "Suffix" },
    fontSize: {
      type: "number",
      default: 96,
      min: 32,
      max: 200,
      step: 2,
      label: "Font size",
    },
    color: { type: "color", default: "#26242c", label: "Color" },
    ease: {
      type: "select",
      default: "in-out",
      options: ["in-out", "out", "linear"],
      label: "Ease",
    },
    seed: { type: "text", default: "count", label: "Seed" },
    step: {
      type: "number",
      default: 3,
      min: 1,
      max: 6,
      step: 1,
      label: "Frames / pose",
    },
  },
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
