import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const handCountConfig: ComponentConfig = {
  componentName: "HandCount",
  importPath: "@/components/remocn/hand-count",
  controls: {
    to: {
      type: "number",
      min: 0,
      max: 10000,
      step: 1,
      default: 1284,
      description: "Count to",
      hiddenFromList: false,
    },
    from: {
      type: "number",
      min: 0,
      max: 1000,
      step: 1,
      default: 0,
      description: "Count from",
      hiddenFromList: false,
    },
    durationSteps: {
      type: "number",
      min: 2,
      max: 24,
      step: 1,
      default: 18,
      description: "Poses counting",
      hiddenFromList: false,
    },
    decimals: {
      type: "number",
      min: 0,
      max: 2,
      step: 1,
      default: 0,
      description: "Decimals",
      hiddenFromList: false,
    },
    prefix: {
      type: "text-content",
      default: "",
      description: "Prefix",
    },
    suffix: {
      type: "text-content",
      default: "",
      description: "Suffix",
    },
    fontSize: {
      type: "number",
      min: 32,
      max: 200,
      step: 2,
      default: 96,
      description: "Font size",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#26242c",
      description: "Color",
    },
    ease: {
      type: "enum",
      default: "in-out",
      variants: {
        "in-out": {},
        out: {},
        linear: {},
      },
      description: "Ease",
    },
    seed: {
      type: "text-content",
      default: "count",
      description: "Seed",
    },
    step: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Frames / pose",
      hiddenFromList: false,
    },
  },
  durationInFrames: 90,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
