import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const inlinePillTakeoverConfig: ComponentConfig = {
  componentName: "InlinePillTakeover",
  importPath: "@/components/remocn/inline-pill-takeover",
  controls: {
    before: {
      type: "text-content",
      default: "powering 20%",
      description: "Text before pill",
    },
    insert: {
      type: "text-content",
      default: "Start building",
      description: "Pill text",
    },
    after: {
      type: "text-content",
      default: "of the Internet.",
      description: "Text after pill",
    },
    fontSize: {
      type: "number",
      min: 24,
      max: 120,
      step: 1,
      default: 52,
      description: "Font size",
      hiddenFromList: false,
    },
    pillWidth: {
      type: "number",
      min: 100,
      max: 600,
      step: 5,
      default: 260,
      description: "Expanded pill width",
      hiddenFromList: false,
    },
    expandFrames: {
      type: "number",
      min: 6,
      max: 45,
      step: 1,
      default: 12,
      description: "Width reveal frames",
      hiddenFromList: false,
    },
    pillRevealHeightScale: {
      type: "number",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 0.35,
      description: "Initial reveal height scale",
      hiddenFromList: false,
    },
    pillGrowAt: {
      type: "number",
      min: 6,
      max: 30,
      step: 1,
      default: 12,
      description: "Pill growth start frame",
      hiddenFromList: false,
    },
    pillGrowFrames: {
      type: "number",
      min: 6,
      max: 36,
      step: 1,
      default: 24,
      description: "Pill growth frames",
      hiddenFromList: false,
    },
    pillGrowWidthScale: {
      type: "number",
      min: 1,
      max: 1.3,
      step: 0.01,
      default: 1.08,
      description: "Final pill width scale",
      hiddenFromList: false,
    },
    pillGrowHeightScale: {
      type: "number",
      min: 1,
      max: 1.5,
      step: 0.01,
      default: 1.16,
      description: "Final pill height scale",
      hiddenFromList: false,
    },
    outerExitFrames: {
      type: "number",
      min: 6,
      max: 30,
      step: 1,
      default: 18,
      description: "Outer text exit frames",
      hiddenFromList: false,
    },
    takeoverAt: {
      type: "number",
      min: 12,
      max: 40,
      step: 1,
      default: 12,
      description: "Camera move start frame",
      hiddenFromList: false,
    },
    takeoverScale: {
      type: "number",
      min: 1,
      max: 4,
      step: 0.05,
      default: 2.15,
      description: "Final takeover scale",
      hiddenFromList: false,
    },
    blur: {
      type: "number",
      min: 0,
      max: 30,
      step: 1,
      default: 12,
      description: "Outer text blur",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#fff3df",
      description: "Outer text color",
    },
    pillColor: {
      type: "color",
      default: "#fffaf0",
      description: "Pill color",
    },
    pillTextColor: {
      type: "color",
      default: "#1c1210",
      description: "Pill text color",
    },
    fontWeight: {
      type: "enum",
      default: "400",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },
  durationInFrames: 45,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: {
    type: "gradient",
    value:
      "radial-gradient(circle at 50% 108%, #ffd77a 0%, #ff6840 31%, #f13d21 78%)",
  },
};
