import {
  CAPTION_FIXTURE,
  previewCaptionsDuration,
  previewTailMs,
} from "@/components/docs/examples/caption-fixture";
import { captionTeleprompterExampleCode } from "@/components/docs/examples/caption-teleprompter-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const captionTeleprompterConfig: ComponentConfig = {
  componentName: "CaptionTeleprompter",
  importPath: "@/components/remocn/caption-teleprompter",
  controls: {
    captions: {
      type: "remotion-captions",
      default: CAPTION_FIXTURE,
      description: "Transcript",
      keyframable: false,
    },
    fontSize: {
      type: "number",
      min: 24,
      max: 140,
      step: 1,
      default: 64,
      description: "Font size",
      hiddenFromList: false,
    },
    fontWeight: {
      type: "number",
      min: 400,
      max: 900,
      step: 100,
      default: 800,
      description: "Font weight",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#ffffff",
      description: "Text color",
    },
    visibleLines: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Visible lines",
      hiddenFromList: false,
    },
    pastOpacity: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.35,
      description: "Past line opacity",
      hiddenFromList: false,
    },
    futureOpacity: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.35,
      description: "Next line opacity",
      hiddenFromList: false,
    },
    upcomingOpacity: {
      type: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.55,
      description: "Unspoken word opacity",
      hiddenFromList: false,
    },
    combineTokensWithinMilliseconds: {
      type: "number",
      min: 0,
      max: 4000,
      step: 100,
      default: 1500,
      description: "Line window (ms)",
      hiddenFromList: false,
    },
    holdMs: {
      type: "number",
      min: 0,
      max: 2000,
      step: 50,
      default: 600,
      description: "Silence break (ms)",
      hiddenFromList: false,
    },
    shadow: {
      type: "boolean",
      default: true,
      description: "Shadow",
    },
  },
  durationInFrames: previewCaptionsDuration(undefined, FPS),
  getDurationInFrames: (values) =>
    previewCaptionsDuration(
      typeof values.captions === "string" ? values.captions : undefined,
      FPS,
      previewTailMs(values.holdMs),
    ),
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#262626" },
  snippet: captionTeleprompterExampleCode,
};
