import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const zoomWordsConfig: ComponentConfig = {
  componentName: "ZoomWords",
  importPath: "@/components/remocn/zoom-words",
  controls: {
    text: {
      type: "text-content",
      default: "Still piecing together tools",
      description: "Text",
    },
    fontSize: {
      type: "number",
      min: 24,
      max: 160,
      step: 1,
      default: 64,
      description: "Font size",
      hiddenFromList: false,
    },
    wordGap: {
      type: "number",
      min: 4,
      max: 24,
      step: 1,
      default: 12,
      description: "Frames / word",
      hiddenFromList: false,
    },
    zoom: {
      type: "number",
      min: 1,
      max: 4,
      step: 0.1,
      default: 2.2,
      description: "Camera zoom",
      hiddenFromList: false,
    },
    anchor: {
      type: "number",
      min: 0.2,
      max: 0.9,
      step: 0.05,
      default: 0.5,
      description: "Camera anchor",
      hiddenFromList: false,
    },
    blur: {
      type: "number",
      min: 0,
      max: 0.3,
      step: 0.01,
      default: 0.04,
      description: "Start blur (em)",
      hiddenFromList: false,
    },
    blurFrames: {
      type: "number",
      min: 10,
      max: 120,
      step: 5,
      default: 60,
      description: "Focus frames",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#cfc2ff",
      description: "Color",
    },
    fontWeight: {
      type: "enum",
      default: "400",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },
  durationInFrames: 75,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: {
    type: "gradient",
    value: "linear-gradient(180deg, #0a0612 25%, #6a3fd6 100%)",
  },
};
