import { checkListExampleCode } from "@/components/docs/examples/check-list-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const checkListConfig: ComponentConfig = {
  componentName: "CheckList",
  importPath: "@/components/remocn/check-list",
  controls: {
    fontSize: {
      type: "number",
      min: 24,
      max: 64,
      step: 2,
      default: 40,
      description: "Font size",
      hiddenFromList: false,
    },
    itemGap: {
      type: "number",
      min: 6,
      max: 48,
      step: 3,
      default: 18,
      description: "Frames between items",
      hiddenFromList: false,
    },
    closeGap: {
      type: "number",
      min: 3,
      max: 24,
      step: 3,
      default: 9,
      description: "Frames between ticks",
      hiddenFromList: false,
    },
    perStep: {
      type: "number",
      min: 0.8,
      max: 3,
      step: 0.2,
      default: 1.6,
      description: "Letters / pose",
      hiddenFromList: false,
    },
    strokeWidth: {
      type: "number",
      min: 1,
      max: 8,
      step: 1,
      default: 3,
      description: "Stroke width",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#26242c",
      description: "Label color",
    },
    tickColor: {
      type: "color",
      default: "#6f7f35",
      description: "Tick color",
    },
    step: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Frames / pose",
      hiddenFromList: false,
    },
  },
  snippet: checkListExampleCode,
  durationInFrames: 360,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
