import { inkUnderlineExampleCode } from "@/components/docs/examples/ink-underline-example";
import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const inkUnderlineConfig: ComponentConfig = {
  componentName: "InkUnderline",
  importPath: "@/components/remocn/ink-underline",
  controls: {
    width: {
      type: "number",
      min: 100,
      max: 800,
      step: 10,
      default: 420,
      description: "Width",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#6f7f35",
      description: "Ink color",
    },
    thickness: {
      type: "number",
      min: 2,
      max: 24,
      step: 1,
      default: 9,
      description: "Brush width",
      hiddenFromList: false,
    },
    pressure: {
      type: "number",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 1,
      description: "Opening pressure",
      hiddenFromList: false,
    },
    release: {
      type: "number",
      min: 0.05,
      max: 1,
      step: 0.05,
      default: 0.15,
      description: "Closing pressure",
      hiddenFromList: false,
    },
    grain: {
      type: "number",
      min: 0,
      max: 2,
      step: 0.1,
      default: 1,
      description: "Grain",
      hiddenFromList: false,
    },
    durationSteps: {
      type: "number",
      min: 2,
      max: 10,
      step: 1,
      default: 5,
      description: "Poses to draw",
      hiddenFromList: false,
    },
    seed: {
      type: "text-content",
      default: "ink",
      description: "Seed",
    },
    step: {
      type: "number",
      min: 1,
      max: 6,
      step: 1,
      default: 3,
      description: "Frames / pose",
      hiddenFromList: false,
    },
  },
  snippet: inkUnderlineExampleCode,
  durationInFrames: 120,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#f1eee7" },
};
