import {
  type ComponentConfig,
  enumVariants,
  FONT_WEIGHT_OPTIONS,
  FPS,
  H,
  W,
} from "@/lib/customizer-config";

export const centeredWordBuildConfig: ComponentConfig = {
  componentName: "CenteredWordBuild",
  importPath: "@/components/remocn/centered-word-build",
  controls: {
    text: {
      type: "text-content",
      default: "everything we learn from",
      description: "Text",
    },
    fontSize: {
      type: "number",
      min: 24,
      max: 160,
      step: 1,
      default: 52,
      description: "Font size",
      hiddenFromList: false,
    },
    wordGap: {
      type: "number",
      min: 4,
      max: 24,
      step: 1,
      default: 11,
      description: "First word gaps",
      hiddenFromList: false,
    },
    accel: {
      type: "number",
      min: 0.4,
      max: 1,
      step: 0.05,
      default: 0.75,
      description: "Later gap multiplier",
      hiddenFromList: false,
    },
    rise: {
      type: "number",
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.18,
      description: "Word rise (em)",
      hiddenFromList: false,
    },
    zoomStep: {
      type: "number",
      min: 0,
      max: 0.1,
      step: 0.005,
      default: 0.035,
      description: "Zoom / word",
      hiddenFromList: false,
    },
    settleFrames: {
      type: "number",
      min: 2,
      max: 20,
      step: 1,
      default: 9,
      description: "Rise and zoom frames",
      hiddenFromList: false,
    },
    exitAt: {
      type: "number",
      min: 20,
      max: 100,
      step: 1,
      default: 51,
      description: "Exit start frame",
      hiddenFromList: false,
    },
    exitFrames: {
      type: "number",
      min: 4,
      max: 30,
      step: 1,
      default: 12,
      description: "Exit duration",
      hiddenFromList: false,
    },
    color: {
      type: "color",
      default: "#fff3df",
      description: "Color",
    },
    fontWeight: {
      type: "enum",
      default: "400",
      variants: enumVariants(FONT_WEIGHT_OPTIONS),
      description: "Font weight",
    },
  },
  durationInFrames: 75,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: {
    type: "gradient",
    value:
      "radial-gradient(circle at 50% 108%, #ffd77a 0%, #ff6840 31%, #f13d21 78%)",
  },
};
